apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-cronjob
            image: anttihanki/todo-cron:0.1.1
            env:
            - name: URL
              value: https://en.wikipedia.org/wiki/Special:Random
            - name: BACKEND_URL
              value: http://todo-backend-svc:1345/todos
          restartPolicy: OnFailure
