apiVersion: v1
kind: Secret
metadata:
    name: todo-db-secret
data:
    POSTGRES_USER: ENC[AES256_GCM,data:9BL5XjNP8VAiwjKl,iv:K5iU+LrwVCyewknwpujFy4gFomwAMGWefrSDgHnLopI=,tag:f2/Pp17ZuqLXqyiUWaL7/A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+IZZJmHAXKWNucjjvBReHA==,iv:T5djbdsDLQa+sWCBAHwiATaJAJbq0vM7b8A1SrH4A5o=,tag:62gur1Av4MqqQJG4zvYlNA==,type:str]
sops:
    age:
        - recipient: age150qmahd3w2tm3s2mvlf0zvcvxgjtqw5dp8ka35a2fxq8hjtd2s4qeu6src
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R0k2RGwrWkZXVjFXWUpB
            SmV6dWw0UHNsSlNuRnZzMWFxUTlaaHBGeXpNCmpOWkhvcGU5WnJHaTF0Wjd5ZlpJ
            R3lsWWJPTGkvaWhMUjA4b291cUJSSUUKLS0tIEg1Q3RTM2pxSllGMWhVVkltYllq
            MTdjSjhaTTRLUGpkUS9Kbm42b2JXZkkKe/5sS+RmeFOSBnsdISvgOwQj9L7j6Ebd
            ZlplOE5sFwPIazNib9LdzvFqp3xaZQeBHbQ7+U35pf8KRTEh7DaCAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T22:53:20Z"
    mac: ENC[AES256_GCM,data:oQ/4bvFqiuTkhO5Rt94s4VeTq51FQ/TNO3kHW8WDsiWVY5VCiQPmhz0hFhl4Eawmd2eBwGAX+3lDqDRJadMflBXzCOXx8tCysw8nc7iUV2II62W9y9J43G0fvJjJA4nQ6cddVHyuG62DXFsdh5PYjn1/bH15KZD1xYHrkkoGLio=,iv:2ijKf+9RHAYZnPci7NIcT03JWRAzF6EyBKXMDuiffjk=,tag:xUPrt7IW52YKy+ZicJDcZA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
