apiVersion: v1
kind: Service
metadata:
  name: todo-db-svc
  namespace: project
  labels: 
    app: todo-db
spec:
  clusterIP: None
  selector:
    app: todo-db
  ports:
  - port: 5432
    name: postgres
  

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-ss
  namespace: project
spec:
  selector:
    matchLabels:
      app: todo-db  
  serviceName: todo-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - name: postgress
        image: postgres:16
        ports:
        - name: postgres
          containerPort: 5432
        envFrom:
        - secretRef:
            name: todo-db-secret
        - configMapRef:
            name: todo-db-config
        volumeMounts:
        - name: data  
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi


