apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
images:
- name: PROJECT/TODO_APP_IMAGE
- name: PROJECT/TODO_BACKEND_IMAGE
- name: PROJECT/TODO_CRONJOB_IMAGE
resources:
  - manifests/config-db.yaml
  - manifests/config.yaml
  - manifests/statefulset.yaml
  - manifests/healthcheckpolicy.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
  - manifests/deployment-backend.yaml
  - manifests/deployment.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/service-backend.yaml
  - manifests/service.yaml
  - manifests/cronjob.yaml
