apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - manifests/config-db.yaml
  - manifests/config.yaml
  - manifests/secret.yaml
  - manifests/statefulset.yaml
  - manifests/healthcheckpolicy.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
  - manifests/deployment-backend.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/service-backend.yaml
  - manifests/service.yaml
  - manifests/cronjob.yaml
