apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pingpong-restart-rate
spec:
  metrics:
  - name: pingpong-restart-rate
    initialDelay: 2m
    successCondition: result < 100
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1769-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          scalar(
            sum(container_cpu_usage_seconds_total{namespace="exercises"}) -
            sum(container_cpu_usage_seconds_total{namespace="exercises"}) offset 5m)
          )