apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: log-output-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: log-output-svc
            port: 
              number: 2345
      - pathType: Prefix
        path: /pingpong
        backend:
          service:
            name: ping-pong-svc
            port: 
              number: 2450
