name: Release todo app

on:
  push:
    paths:
      - 'the_project/todo-app/**'
      - 'the_project/todo-backend/**'
      - 'the_project/todo-cron/**'
      - 'the_project/manifests/**'
      - '.github/workflows/main.yaml'
    
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: dwk-repo
  BUILD_CONTEXT_APP: the_project/todo-app
  BUILD_CONTEXT_BACKEND: the_project/todo-backend
  BUILD_CONTEXT_CRONJOB: the_project/todo-cron
  IMAGE_APP: todo-app
  IMAGE_BACKEND: todo-backend
  IMAGE_CRONJOB: todo-cronjob
  SERVICE_APP: todo-app-dep
  SERVICE_BACKEND: todo-backend-dep
  KUSTOMIZE_PATH: the_project
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker "$REGISTRY"

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'
      
      - name : 'Form image names'
        run: |
          echo "IMAGE_TAG_APP=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_APP:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG_BACKEND=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_BACKEND:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG_CRONJOB=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_CRONJOB:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build --tag "$IMAGE_TAG_APP" "$BUILD_CONTEXT_APP"
          docker build --tag "$IMAGE_TAG_BACKEND" "$BUILD_CONTEXT_BACKEND"
          docker build --tag "$IMAGE_TAG_CRONJOB" "$BUILD_CONTEXT_CRONJOB"

      - name: Publish
        run: |
          docker push "$IMAGE_TAG_APP"
          docker push "$IMAGE_TAG_BACKEND"
          docker push "$IMAGE_TAG_CRONJOB"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Set namespace main
        if: github.ref_name == 'main'
        run: |
          echo "NAMESPACE=project" >> $GITHUB_ENV

      - name: Set namespace not main
        if: github.ref_name != 'main'
        run: |
          echo "NAMESPACE=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          
      - name: Deploy
        run: |-
          cd $KUSTOMIZE_PATH
          kubectl create namespace "$NAMESPACE" || true
          kubectl config set-context --current --namespace="$NAMESPACE"

          kubectl create secret generic todo-db-secret \
            --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -n "$NAMESPACE" \
            --dry-run=client -o yaml | kubectl apply -f -

          kustomize edit set namespace "$NAMESPACE"
          kustomize edit set image PROJECT/TODO_APP_IMAGE="$IMAGE_TAG_APP"
          kustomize edit set image PROJECT/TODO_BACKEND_IMAGE="$IMAGE_TAG_BACKEND"
          kustomize edit set image PROJECT/TODO_CRONJOB_IMAGE="$IMAGE_TAG_CRONJOB"
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $SERVICE_APP -n "$NAMESPACE"
          kubectl rollout status deployment $SERVICE_BACKEND -n "$NAMESPACE"
          kubectl get services -o wide
